language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mrossi93
  password:
    secure: Ncw9dJopRywYs/y6OFBONlPHRuNgZxNdhU8ZCfQMziohxa8WbutR7MG+yCYKBy5s+Pyb//cKl3eNN+LKq5/rrawaFGKoj2iLLLLsiHdfWUOFyLiJhkhqAYRp18HvtaMJ34uObJS3wDOcZJzHIX3mAbq6WEisbqPj9kreJC8CvVLipw+AZIKaa52QZaWeeIp2u22Isg2XK6pVyaQHq4PdWlvTtKCvwFESmXB02xEH+ePHNPlSjcbQlG73MoOw4Trm588MZ6ZAwtJQIdkSnSUKCS6HC7py1FNbY8MU2tJIXyEdxmncEKxNlxt5zw7iS5rMpa0jn7dxApnhnLyHk6gJy5iwD01zx6sqGDFvJvifI1Li47Ta/HHCgqEi7MAVQ+077TLVH71Mvy6X8/6uyWanmH3mhDMB3+ieVGgTNADpQUY3LrNBr/32PgsHg0usoC50hpfrhr/8K9OlUB831zVmkfUhIFUb6NzR6aUG28dMuzsL357RvWecd/d53hqkqGkrtRt+EIzKSeoldj9Gb0f2im3xtoC3I8vw8WEsqiIPRd25c13aYTgRzzYDGYefbXzZygguBs97CW+0MjzDKduIOzM/sQmILcO1RE55EAS89ma3F5uf8qhrN9keMZ3NPjs68YkqRkLUCVJq1/YOvioHMHMSla7ZCUjD2on25c7iXOk=
  on:
    tags: true
    repo: mrossi93/rw_calibration
    python: 3.8
