language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: cJRpXdJmc1kaYGHUsObuAY1HLsmLVTjrQYfBA17fezLtglccQNYftlfs6IlMzWz+iea79DI00S7itwCN2Lpj4PtDzNzP28OQB5Dbp9kEWoDynhmggYPIwG6XJtZU/H/Vc2rILP6jI90aa6lqOgLfrRUAfITGDVkdqyzytf7/EurzCvvbQGtpLMy97yLqXlf4SJW60V4uec7a3WWZehBbnczUXYC2UdSZ5H4I1i9t5fhOfWv9Weg0J3dO/gnvNxNpsM4Md3Avf4+T7/ZrCPGkKoPt/Vp2X0L7tSktQoentP99haHACUXZAZSHA6eiSI1zI8nFW+yksNUVZPpEZt/hLRvvLkTlSlo9mqg+XbM/KGYQnUq4ORECglXzibqcPTPJRzB2ncBnrbbDvN03qmuCD6ZK30TK4RZgDJOJ2AVUeuK2VV8/YXEW2rwC7yLAQ6/aB/m1nyqe0d+SmmRXIpoP+oCE4WkZGr/NRvwS2R6nmfpalRNKlGZAuakyCMwjL4Unh4oEVr6n4XPV1CSFJH+MDRoi2OhW6UHtjFBsCWjHb0RwmFx9YBiZDJznW94UotZ0x5yettXazTzA7+SvGQFkbhOMnpR9vD2SV5i9YSwp7XjvG1/zXRpuz/9tV8s4C0wtG3/zFN/am7I1ajKw8rLpItoKGhxjSLCIoINnD0yfagA=
  on:
    tags: true
    repo: mrossi93/rw_calibration
    python: 3.8
